from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional, Any, Dict

class EducationSchema(BaseModel):
    """Schema representing education history entries parsed from a resume."""
    institution: Optional[str] = Field(None, description="Name of the university or school")
    degree: Optional[str] = Field(None, description="Degree obtained, e.g., Bachelor, Master")
    year: Optional[str] = Field(None, description="Graduation year or duration")

class WorkExperienceSchema(BaseModel):
    """Schema representing professional work experience entries parsed from a resume."""
    # Use ConfigDict for modern Pydantic V2 configuration management
    model_config = ConfigDict(populate_by_name=True)

    company: Optional[str] = Field(None, description="Company name")
    role: Optional[str] = Field(None, alias="job_title", description="Job title or designation") 
    duration: Optional[str] = Field(None, description="Time period of employment")
    description: Optional[str] = Field(None, description="Brief responsibilities description")

class StructuredResumeResponse(BaseModel):
    """Schema representing the complete structured AI analysis output for a resume."""
    full_name: Optional[str] = Field(None, description="Candidate's extracted full name")
    email: Optional[str] = Field(None, description="Candidate's email address")
    phone: Optional[str] = Field(None, description="Candidate's phone number")
    linkedin: Optional[str] = Field(None, description="LinkedIn profile URL")
    github: Optional[str] = Field(None, description="GitHub profile URL")
    location: Optional[str] = Field(None, description="City and Country location")
    summary: Optional[str] = Field(None, description="Extracted profile professional summary")
    skills: List[str] = Field(default_factory=list, description="List of technical and soft skills") 
    languages: List[str] = Field(default_factory=list, description="Languages spoken by the candidate")
    education_history: List[EducationSchema] = Field(default_factory=list, description="List of educational backgrounds")
    work_history: List[WorkExperienceSchema] = Field(default_factory=list, description="List of professional job histories")
    projects: List[Any] = Field(default_factory=list, description="Personal or academic projects mentioned")
    ai_overall_evaluation: str = Field(..., description="Comprehensive professional expert review generated by AI")
    ats_score: int = Field(0, ge=0, le=100, description="ATS compatibility score from 0 to 100")

class JobMatchResultSchema(BaseModel):
    """Schema representing the AI matching output between a specific resume and a job description."""
    match_percentage: int = Field(..., ge=0, le=100, description="Overall matching percentage score")
    matching_skills: List[str] = Field(default_factory=list, description="Skills present in both resume and job post")
    missing_skills: List[str] = Field(default_factory=list, description="Required skills missing from the candidate's resume")
    section_scores: Dict[str, int] = Field(
        default_factory=lambda: {"skills": 0, "experience": 0, "education": 0},
        description="Detailed categorical breakdowns of matching scores"
    )
    explanation: str = Field(..., description="Professional textual explanation justifying the matching scores")